### ISSUE TITLE
Uncaught ReferenceError: python is not defined

### ISSUE THREAD

**Issue by MSS-OOO** [atom-community/ide-python#336] opened 2021-06-09 14:09 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.1

### Stack Trace

Uncaught ReferenceError: python is not defined

```
At C:\Users\mshelopugin\.atom\packages\ide-python\dist\main.js:117

ReferenceError: python is not defined
    at PythonLanguageClient.onSpawnClose (/packages/ide-python/dist/main.js:117:96)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:393:54)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
emmet 2.4.3 
ide-python 1.9.1 
remote-ftp 2.2.4 
script 3.32.2 
```

**Comment by ThatXliner** [comment] 2021-06-09 16:24
Possible duplicate of #335

**Closed** 2021-06-10 06:30 UTC
