### ISSUE TITLE
Automatically install atom-ide-base

### ISSUE THREAD

**Issue by jsaxx** [atom-community/ide-python#209] opened 2020-09-18 15:40 UTC
I have installed atom-ide-ui, and ide-python packages. Python and pyls are installed as well to the latest versions. Nonetheless I am not able to use any of the functions the packages should provide (e.g. autocomplete, highlighting, etc.), they just do not seem to be active.

I have tried to set the python-ide Python Executable path to the actual install path (C:\Python\Python38-32\python.exe), as I though it could be a problem with the defaults. Still nothing.

I am wondering if I am missing any import step in the setup, or if I am using something wrongly.

**Comment by mwielondek** [comment] 2020-10-08 13:36
To add to this; I'm confused as to whether you still need the `atom-ide-ui` package, despite it being removed as dependency from the readme. Without it, however, I can't seem to figure out how to use the code formatting options etc. Any clarification on this would be appreciated.

**Comment by utkarshgupta137** [comment] 2020-10-16 14:55
@mwielondek +1

**Comment by aminya** [comment] 2020-10-30 00:28
You need to install [atom-ide-base](https://atom.io/packages/atom-ide-base)

**Comment by SecT0uch** [comment] 2020-11-11 16:11
I have a similar issue:

I uninstalled `atom-ide-ui` and `python-ide`, installed `atom-ide-base` instead and reinstalled `python-ide`.

However it doesn't seem to work.

Do I necessary have to use your atom fork for that to work ?

**Comment by aminya** [comment] 2020-11-11 16:17
> I have a similar issue:
> 
> I uninstalled `atom-ide-ui` and `python-ide`, installed `atom-ide-base` instead and reinstalled `python-ide`.
> 
> However it doesn't seem to work.
> 
> Do I necessary have to use your atom fork for that to work ?

@SecT0uch No, it works with the official releases as well. Do you get any errors/messages?

**Comment by SecT0uch** [comment] 2020-11-11 16:26
> @SecT0uch No, it works with the official releases as well. Do you get any errors/messages?

Nope, nothing at all (I tried a factory reset with no help). I have nothing regarding that in the console

**Comment by aminya** [comment] 2020-11-11 16:30
Could you install `atom-ide-javascript` and check if the datatips are shown inside a JavaScript file? I just want to see if the problem is with ide-python or it is with atom-ide-base

**Comment by SecT0uch** [comment] 2020-11-11 16:36
My bad, I do have completion.
Do I need to install the debugger for pycodestyle warnings, etc ?

**Comment by aminya** [comment] 2020-11-11 16:38
You should go to settings and enable them!
![image](https://user-images.githubusercontent.com/16418197/98838569-0eb5cb00-240a-11eb-9508-cbf53ba8eb50.png)

**Comment by SecT0uch** [comment] 2020-11-11 16:43
It is enabled.
 I can't find the Diagnostics window were errors and warning normally appear. Nothing is underlined (and some warning should show up)

**Comment by aminya** [comment] 2020-11-11 16:49
Do you have `linter-ui-default` and `linter` installed?

**Comment by SecT0uch** [comment] 2020-11-11 16:53
`linter-ui-default` was not installed (should it be in the dependencies?). 
I can now open the Linter panel, but still nothing shows up.

**Comment by aminya** [comment] 2020-11-11 16:57
> linter-ui-default was not installed (should it be in the dependencies?).

No just install it from the settings page of Atom. I am wondering why `atom-ide-base` does not install it for you automatically! 

In order to get the warnings, you need to have linter, linter-ui-default, and ide-python installed and enabled. Try restarting Atom.

**Comment by SecT0uch** [comment] 2020-11-11 17:07
After install the new version:

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: "Manjaro Linux"
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.6.1


### Stack Trace

Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

```
At /home/jordan/.atom/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:16

TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Fa (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:113:292)
    at /packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:27:339)
    at a._innerSub (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:416)
    at a._tryNext (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:320)
    at a._next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:148)
    at a.next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:65:253)
    at a.notifyNext (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:120:125)
    at a._next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:116:50)
    at a.next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:65:253)
    at /packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:94:79
    at /packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:27:344)
    at a._innerSub (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:416)
    at a._tryNext (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:320)
    at a._next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:148)
    at a.next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:65:253)
    at b._subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:94:79)
    at b._trySubscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:376)
    at b.subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:161)
    at b.call (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:118:338)
    at b.subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:34)
    at b.call (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:118:338)
    at b.subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:34)
    at b.call (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:118:338)
    at b.subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:34)
    at listenToRemoteDebugCommands (/packages/ide-python/dist/debugger/utils.js:85:6)
    at activate (/packages/ide-python/dist/debugger/main.js:34:92)
    at PythonLanguageClient.activate (/packages/ide-python/dist/main.js:47:24)
    at Package.activateNow (/usr/lib/atom/src/package.js:241:27)
    at /usr/lib/atom/src/package.js:1058:18
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
```

### Commands

```
     -2:06.1.0 typescript:activate (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-ide-base 2.1.1 
atom-ide-javascript 1.5.0 
atom-typescript 14.0.3 
autocomplete-paths 2.12.6 
busy-signal 2.0.1 
ide-python 1.6.1 
intentions 1.1.5 
javascript-drag-import 0.1.13 
linter 3.1.1 
linter-eslint 8.5.5 
linter-ui-default 2.1.4 
```

**Comment by SecT0uch** [comment] 2020-11-11 17:10
But I can confirm the code linting works now, despite the error! :)

**Comment by aminya** [comment] 2020-11-11 17:12
@SecT0uch Thanks for the answers! It helps us to find and fix the bugs!

> Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

I thought that this was fixed in the last version of atom-ide-debugger. I take a look.

**Comment by Zerox91** [comment] 2021-01-04 12:30
```
Linux Mint 20.0
Atom 1.53.0
atom-ide-base 2.1.1
ide-python 1.7.1
```

Same issue, no errors or warnings show up.
Installing `linter` and `linter-ui-default` resolve the issue.
Was working fine with `atom-ide-ui`

**Comment by TianshuangQiu** [comment] 2021-01-24 20:44
Same issue, but installing linter packages does not seem to help. I think my Pyls server may be bugged.

**Comment by aflueckiger** [comment] 2021-04-04 10:23
Same issue here. The only think that is working is the `Debugger`. Other functionality doesn't show up in the UI. All packages are installed via `apm` and are up to date. 

```
atom --version
Atom    : 1.55.0
Electron: 6.1.12
```

```
Community Packages (16) /home/alex/.atom/packages
├── atom-ide-base@2.6.0
├── atom-ide-console@0.0.2
├── atom-ide-datatip@0.24.1
├── atom-ide-debugger@0.0.3
├── atom-ide-definitions@0.4.1
├── atom-ide-hyperclick@1.0.9
├── atom-ide-markdown-service@2.1.0
├── atom-ide-outline@2.3.1
├── atom-ide-signature-help@0.15.3
├── busy-signal@2.0.1
├── ide-python@1.8.0
├── intentions@1.1.5 (disabled)
├── linter@3.3.1
├── linter-flake8@2.4.0
├── linter-ui-default@3.3.1
└── python-black@0.7.0
```

**Closed** 2021-06-09 11:02 UTC
