### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by 84-16** [atom-community/ide-python#298] opened 2021-03-22 15:35 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.4

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\29056\.atom\packages\ide-python\node_modules\@atom-ide-community\nuclide-debugger-common\node_modules\react\index.js
- C:\Users\29056\.atom\packages\ide-python\node_modules\@atom-ide-community\nuclide-debugger-common\DebuggerLaunchAttachProvider.js
- C:\Users\29056\.atom\packages\ide-python\node_modules\@atom-ide-community\nuclide-debugger-common\AutoGenLaunchAttachProvider.js
- C:\Users\29056\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\29056\.atom\packages\ide-python\dist\main.js
- C:\Users\29056\AppData\Local\atom\app-1.55.0\resources\app.asar\static\index.html

Error: Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\29056\.atom\packages\ide-python\node_modules\@atom-ide-community\nuclide-debugger-common\node_modules\react\index.js
- C:\Users\29056\.atom\packages\ide-python\node_modules\@atom-ide-community\nuclide-debugger-common\DebuggerLaunchAttachProvider.js
- C:\Users\29056\.atom\packages\ide-python\node_modules\@atom-ide-community\nuclide-debugger-common\AutoGenLaunchAttachProvider.js
- C:\Users\29056\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\29056\.atom\packages\ide-python\dist\main.js
- C:\Users\29056\AppData\Local\atom\app-1.55.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/atom-ide-ui/node_modules/react/index.js:4:20)
    at /packages/atom-ide-ui/node_modules/react/index.js:9:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/DebuggerLaunchAttachProvider.js:8:37)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/DebuggerLaunchAttachProvider.js:75:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:10:60)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/debugger/main.js:16:36)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-python-run 0.9.7 
ide-python 1.7.4 
```

**Comment by aminya** [comment] 2021-06-10 07:52
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919

Duplicate of #330

**Closed by aminya** 2021-06-10 07:52 UTC
