### ISSUE TITLE
Uncaught ReferenceError: python is not defined

### ISSUE THREAD

**Issue by ddecker618** [atom-community/ide-python#339] opened 2021-06-09 17:39 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.4
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.1

### Stack Trace

Uncaught ReferenceError: python is not defined

```
At /Users/ddecker/.atom/packages/ide-python/dist/main.js:117

ReferenceError: python is not defined
    at PythonLanguageClient.onSpawnClose (/packages/ide-python/dist/main.js:117:96)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:393:54)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:228:7)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
     -0:36.2.0 application:add-project-folder (div.tool-panel.tree-view)
     -0:19.4.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
busy-signal 2.0.1 
dbg 1.6.3 
gdb-debug 0.0.3 
Hydrogen 2.16.3 
ide-python 1.9.1 
intentions 1.1.5 
line-number-color 0.2.0 
linter 3.3.1 
linter-clang 4.1.2 
linter-gcc 0.9.0 
linter-ui-default 3.3.1 
output-panel 0.3.4 
platformio-ide-terminal 2.10.1 
project-manager 3.3.8 
reindent-line 0.2.0 
script 3.32.2 
teletype 0.13.4 
```

**Comment by ThatXliner** [comment] 2021-06-09 19:29
Possible duplicate of #335

**Closed** 2021-06-10 07:14 UTC
