### ISSUE TITLE
Uncaught ReferenceError: python is not defined

### ISSUE THREAD

**Issue by sruju333** [atom-community/ide-python#337] opened 2021-06-09 15:38 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.3.1
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.1

### Stack Trace

Uncaught ReferenceError: python is not defined

```
At /Users/srujana/.atom/packages/ide-python/dist/main.js:117

ReferenceError: python is not defined
    at PythonLanguageClient.onSpawnClose (/packages/ide-python/dist/main.js:117:96)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:393:54)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
     -0:16 application:reopen-project (div#add-projects-view.)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-base 2.6.0 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.10 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 2.3.4 
atom-ide-signature-help 0.16.0 
busy-signal 2.0.1 
file-icons 2.1.47 
ide-python 1.9.1 
intentions 1.1.5 
linter 3.3.1 
linter-ui-default 3.3.1 
minimap 4.39.14 
nord-atom-ui 0.12.0 
platformio-ide-terminal 2.10.1 
script 3.32.2 
```

**Comment by ThatXliner** [comment] 2021-06-09 16:24
Possible duplicate of #335

**Closed** 2021-06-10 06:30 UTC
