### ISSUE TITLE
Uncaught ReferenceError: python is not defined

### ISSUE THREAD

**Issue by soniyag7** [atom-community/ide-python#340] opened 2021-06-09 17:56 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.1

### Stack Trace

Uncaught ReferenceError: python is not defined

```
At C:\Users\Sonlya\.atom\packages\ide-python\dist\main.js:117

ReferenceError: python is not defined
    at PythonLanguageClient.onSpawnClose (/packages/ide-python/dist/main.js:117:96)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:393:54)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

### Commands

```
  3x -4:17.2.0 fuzzy-finder:toggle-git-status-finder (input.hidden-input)
     -3:51.5.0 window:increase-font-size (input.hidden-input)
 36x -3:50.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
ide-python 1.9.1 
script 3.32.2 
```

**Comment by ThatXliner** [comment] 2021-06-09 19:29
Possible duplicate of #335

**Closed** 2021-06-10 07:13 UTC
